### ISSUE TITLE
Market bid with state causes exception when verbose is enabled

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1110]
A call to market/bid.cpp:submit_bid_state() when global verbose is TRUE causes a SIGSEGV as follows:

~~~~
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6da26e4 in vfprintf () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.172.amzn1.x86_64
(gdb) where
#0  0x00007ffff6da26e4 in vfprintf () from /lib64/libc.so.6
#1  0x00007ffff6dc7aab in vsprintf () from /lib64/libc.so.6
#2  0x0000000000456a4c in output_verbose ()
#3  0x00007fffdca932a1 in submit_bid_state () from /usr/local/lib/gridlabd/market.so
#4  0x00007fffdca9c8f4 in controller::sync(long long, long long) () from /usr/local/lib/gridlabd/market.so
#5  0x00007fffdca9e393 in sync_controller () from /usr/local/lib/gridlabd/market.so
#6  0x0000000000452384 in _object_sync ()
#7  0x00000000004524e8 in object_sync ()
#8  0x0000000000427956 in ss_do_object_sync ()
#9  0x000000000042978b in exec_start ()
#10 0x000000000042608d in environment_start ()
#11 0x0000000000414af9 in main ()
~~~~

The problem is causes by an incorrect format specifier in the stateful gl_verbose call in market/bid.cpp.  The specification is "%s" but the value is an int.

There are two possible fixes.  The simplest is to change the specification to "%d".  A better solution is to use state to index into a list of string that correspond to the state values (after a check for whether it is valid).

**Comment by trevorhardy** [comment]
Closing per recommendation.
